site_name: lyn
site_url: https://slynj.github.io/tech-docs/
theme:
  name: material

  palette: 
    
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Inter

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.follow
    - content.code.copy
    - content.code.select

nav:
  - Home: index.md
  - 5G-Network:
    - 5G Core - Building Open5GS: "5G-Network/5G Core - Building Open5GS 17e011ff45b98048a6aff1a15e6d60a5.md"
    - 5G UE & RAN - Building UERANSIM: "5G-Network/5G UE & RAN with UERANSIM 17e011ff45b98023b13bc0a753286816.md"
    - 5G end-to-end Build and Deployment with UERANSIM & Open5GS: "5G-Network/5G end-to-end Build and Deployment with UERANSIM & 17e011ff45b980c499b7e6dffb96bb93.md"
  - Machine Learning:
    - Data Visualization:
      - Correlation Heatmap with Seaborn: "ML/Visualization/Correlation Heatmap with Seaborn 18a011ff45b980ad8f63d0cfeeb659ca.md"
    - Clustering:
      - DBSCAN: "ML/Clustering/DBSCAN 19e011ff45b98096b93ffb033d1bba4d.md"
      - Mean-Shift Clustering: "ML/Clustering/Mean-Shift Clustering 19e011ff45b9803c83d2e0856dbeaada.md"
    - Neural Network:
      - Hopfield Neural Network: "ML/Neural-Network/Hopfield Neural Network 1a0011ff45b98006ba09f1ae55d72527.md"
  - Commands/Tools:
    - Change Hostname on Linux with CLI: "Commands/Change Hostname on Linux with CLI 181011ff45b980e38a50eea810ec0493.md"
  - C++:
    - Fast Logging for C++ with spdlog: "C++/spdlog - Fast Logging for C++ 188011ff45b980fbaf27d4fbf13f449d.md"
    - Simple REST API Implementation in C++ with nghttp2, jsoncpp: "C++/Simple REST API Implementation in C++ with nghttp2 189011ff45b980a49b60c4a7cd6d2c2c.md"
    - Event-Driven Architecture (EDA) in C++ with RabbitMQ (SimpleAmqpClient): "C++/Event-Driven Architecture (EDA) in C++ with Rabbit 18b011ff45b980f79c83ef50b32b2910.md"

markdown_extensions:
  - toc:
      permalink: true
  -  codehilite:
      guess_lang: false
      use_pygments: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - stylesheets/custom.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js

extra:
  generator: false

plugins:
  - search:
      lang: en
      separator: "[\\s\\-]+"

